name: easy_image_viewer
description: An easy image viewer with pinch & zoom, multi image, and built-in full-screen dialog support.
version: 1.5.1
homepage: https://github.com/thesmythgroup/easy_image_viewer

environment:
  sdk: ">=2.19.0 <4.0.0"  # This implies at least Dart 2.19, which comes with Flutter 3.7.0
  flutter: ">=3.7.0"

topics:
  - image
  - photo
  - slideshow
  - pager
  - zoom

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.3
