name: easy_image_viewer
description: An easy image viewer with pinch & zoom, multi image, and built-in full-screen dialog support.
version: 1.4.0
homepage: https://github.com/thesmythgroup/easy_image_viewer

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

topics:
  - image
  - photo
  - slideshow
  - pager
  - zoom

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
